# _config.yml, 32line 코드
comments:
  provider:
    "disqus" # comment 처리 사이트 명칭 기재
    # false (default), "disqus", "discourse", "facebook"
    # "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname:
      "eona1301-github-io" # disqus의 shortname 기재
      # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# _config.yml, 270line 코드

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
